# Generated by Django 6.0.6 on 2026-06-10 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('emoji', models.CharField(max_length=10)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reviews', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('badge', models.CharField(blank=True, max_length=10)),
                ('sizes', models.CharField(blank=True, max_length=255)),
                ('desc', models.TextField()),
                ('material', models.CharField(max_length=255)),
                ('origin', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=255)),
            ],
        ),
    ]
