# Generated by Django 6.0.6 on 2026-06-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_cart_delete_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.JSONField(default={}),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
